export const value = [
    {
        "name": "Mercury Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "1",
        "cost": "3000",
        "currency": "INR",
        "logoImage": "Mercury.png",
        "status": "Available Book Now",
        "flghtnumber": "MERC001"
    },
    {
        "name": "Venus Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "1.5",
        "cost": "3050",
        "currency": "INR",
        "logoImage": "Venus.png",
        "status": "Available Book Now",
        "flghtnumber": "VENU001"
    },
    {
        "name": "Earth Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "2",
        "cost": "3100",
        "currency": "INR",
        "logoImage": "Earth.png",
        "status": "Available Book Now",
        "flghtnumber": "EART001"
    },
    {
        "name": "Mars Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "2.5",
        "cost": "3150",
        "currency": "INR",
        "logoImage": "Mars.png",
        "status": "Available Book Now",
        "flghtnumber": "MARS001"
    },
    {
        "name": "Jupiter Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "3",
        "cost": "3200",
        "currency": "INR",
        "logoImage": "Jupiter.png",
        "status": "Available Book Now",
        "flghtnumber": "JUPI001"
    },
    {
        "name": "Saturn Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "3.5",
        "cost": "3250",
        "currency": "INR",
        "logoImage": "Saturn.png",
        "status": "Available Book Now",
        "flghtnumber": "SATU001"
    },
    {
        "name": "Uranus Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "4",
        "cost": "3300",
        "currency": "INR",
        "logoImage": "Uranus.png",
        "status": "Available Book Now",
        "flghtnumber": "URAN001"
    },
    {
        "name": "Neptune Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "4.5",
        "cost": "3350",
        "currency": "INR",
        "logoImage": "Neptune.png",
        "status": "Available Book Now",
        "flghtnumber": "NEPT001"
    },
    {
        "name": "Pluto Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "5",
        "cost": "3400",
        "currency": "INR",
        "logoImage": "Pluto.png",
        "status": "Available Book Now",
        "flghtnumber": "PLUT001"
    },
    {
        "name": "Mercury Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "1",
        "cost": "3450",
        "currency": "INR",
        "logoImage": "Mercury.png",
        "status": "Unavailable",
        "flghtnumber": "MERC002"
    },
    {
        "name": "Venus Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "1.5",
        "cost": "3500",
        "currency": "INR",
        "logoImage": "Venus.png",
        "status": "Unavailable",
        "flghtnumber": "VENU002"
    },
    {
        "name": "Earth Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "2",
        "cost": "3550",
        "currency": "INR",
        "logoImage": "Earth.png",
        "status": "Unavailable",
        "flghtnumber": "EART002"
    },
    {
        "name": "Mars Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "2.5",
        "cost": "3600",
        "currency": "INR",
        "logoImage": "Mars.png",
        "status": "Unavailable",
        "flghtnumber": "MARS002"
    },
    {
        "name": "Jupiter Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "3",
        "cost": "3650",
        "currency": "INR",
        "logoImage": "Jupiter.png",
        "status": "Unavailable",
        "flghtnumber": "JUPI002"
    },
    {
        "name": "Saturn Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "3.5",
        "cost": "3700",
        "currency": "INR",
        "logoImage": "Saturn.png",
        "status": "Unavailable",
        "flghtnumber": "SATU002"
    },
    {
        "name": "Uranus Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "4",
        "cost": "3750",
        "currency": "INR",
        "logoImage": "Uranus.png",
        "status": "Unavailable",
        "flghtnumber": "URAN002"
    },
    {
        "name": "Neptune Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "4.5",
        "cost": "3800",
        "currency": "INR",
        "logoImage": "Neptune.png",
        "status": "Unavailable",
        "flghtnumber": "NEPT002"
    },
    {
        "name": "Pluto Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "5",
        "cost": "3850",
        "currency": "INR",
        "logoImage": "Pluto.png",
        "status": "Unavailable",
        "flghtnumber": "PLUT002"
    },
    {
        "name": "Mercury Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "1",
        "cost": "3900",
        "currency": "INR",
        "logoImage": "Mercury.png",
        "status": "Check Status",
        "flghtnumber": "MERC002"
    },
    {
        "name": "Venus Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "1.5",
        "cost": "3950",
        "currency": "INR",
        "logoImage": "Venus.png",
        "status": "Check Status",
        "flghtnumber": "VENU002"
    },
    {
        "name": "Earth Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "2",
        "cost": "4000",
        "currency": "INR",
        "logoImage": "Earth.png",
        "status": "Check Status",
        "flghtnumber": "EART002"
    },
    {
        "name": "Mars Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "2.5",
        "cost": "4050",
        "currency": "INR",
        "logoImage": "Mars.png",
        "status": "Check Status",
        "flghtnumber": "MARS002"
    },
    {
        "name": "Jupiter Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "3",
        "cost": "4100",
        "currency": "INR",
        "logoImage": "Jupiter.png",
        "status": "Check Status",
        "flghtnumber": "JUPI002"
    },
    {
        "name": "Saturn Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "3.5",
        "cost": "4150",
        "currency": "INR",
        "logoImage": "Saturn.png",
        "status": "Check Status",
        "flghtnumber": "SATU002"
    },
    {
        "name": "Uranus Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "4",
        "cost": "4200",
        "currency": "INR",
        "logoImage": "Uranus.png",
        "status": "Check Status",
        "flghtnumber": "URAN002"
    },
    {
        "name": "Neptune Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "4.5",
        "cost": "4250",
        "currency": "INR",
        "logoImage": "Neptune.png",
        "status": "Check Status",
        "flghtnumber": "NEPT002"
    },
    {
        "name": "Pluto Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "5",
        "cost": "4300",
        "currency": "INR",
        "logoImage": "Pluto.png",
        "status": "Check Status",
        "flghtnumber": "PLUT002"
    },
    {
        "name": "Mercury Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "1",
        "cost": "4350",
        "currency": "INR",
        "logoImage": "Mercury.png",
        "status": "Checking Status",
        "flghtnumber": "MERC003"
    },
    {
        "name": "Venus Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "1.5",
        "cost": "4400",
        "currency": "INR",
        "logoImage": "Venus.png",
        "status": "Checking Status",
        "flghtnumber": "VENU003"
    },
    {
        "name": "Earth Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "2",
        "cost": "4450",
        "currency": "INR",
        "logoImage": "Earth.png",
        "status": "Checking Status",
        "flghtnumber": "EART003"
    },
    {
        "name": "Mars Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "2.5",
        "cost": "4500",
        "currency": "INR",
        "logoImage": "Mars.png",
        "status": "Checking Status",
        "flghtnumber": "MARS003"
    },
    {
        "name": "Jupiter Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "3",
        "cost": "4550",
        "currency": "INR",
        "logoImage": "Jupiter.png",
        "status": "Checking Status",
        "flghtnumber": "JUPI003"
    },
    {
        "name": "Saturn Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "3.5",
        "cost": "4600",
        "currency": "INR",
        "logoImage": "Saturn.png",
        "status": "Checking Status",
        "flghtnumber": "SATU003"
    },
    {
        "name": "Uranus Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "4",
        "cost": "4650",
        "currency": "INR",
        "logoImage": "Uranus.png",
        "status": "Checking Status",
        "flghtnumber": "URAN003"
    },
    {
        "name": "Neptune Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "4.5",
        "cost": "4700",
        "currency": "INR",
        "logoImage": "Neptune.png",
        "status": "Checking Status",
        "flghtnumber": "NEPT003"
    },
    {
        "name": "Pluto Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "5",
        "cost": "4750",
        "currency": "INR",
        "logoImage": "Pluto.png",
        "status": "Checking Status",
        "flghtnumber": "PLUT003"
    },
    {
        "name": "Mercury Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "1",
        "cost": "4800",
        "currency": "INR",
        "logoImage": "Mercury.png",
        "status": "Available Book Now",
        "flghtnumber": "MERC003"
    },
    {
        "name": "Venus Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "1.5",
        "cost": "4850",
        "currency": "INR",
        "logoImage": "Venus.png",
        "status": "Available Book Now",
        "flghtnumber": "VENU003"
    },
    {
        "name": "Earth Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "2",
        "cost": "4900",
        "currency": "INR",
        "logoImage": "Earth.png",
        "status": "Available Book Now",
        "flghtnumber": "EART003"
    },
    {
        "name": "Mars Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "2.5",
        "cost": "4950",
        "currency": "INR",
        "logoImage": "Mars.png",
        "status": "Available Book Now",
        "flghtnumber": "MARS003"
    },
    {
        "name": "Jupiter Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "3",
        "cost": "5000",
        "currency": "INR",
        "logoImage": "Jupiter.png",
        "status": "Available Book Now",
        "flghtnumber": "JUPI003"
    },
    {
        "name": "Saturn Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "3.5",
        "cost": "5050",
        "currency": "INR",
        "logoImage": "Saturn.png",
        "status": "Available Book Now",
        "flghtnumber": "SATU003"
    },
    {
        "name": "Uranus Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "4",
        "cost": "5100",
        "currency": "INR",
        "logoImage": "Uranus.png",
        "status": "Available Book Now",
        "flghtnumber": "URAN003"
    },
    {
        "name": "Neptune Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "4.5",
        "cost": "5150",
        "currency": "INR",
        "logoImage": "Neptune.png",
        "status": "Available Book Now",
        "flghtnumber": "NEPT003"
    },
    {
        "name": "Pluto Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "5",
        "cost": "5200",
        "currency": "INR",
        "logoImage": "Pluto.png",
        "status": "Available Book Now",
        "flghtnumber": "PLUT003"
    },
    {
        "name": "Mercury Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "1",
        "cost": "5250",
        "currency": "INR",
        "logoImage": "Mercury.png",
        "status": "Unavailable",
        "flghtnumber": "MERC004"
    },
    {
        "name": "Venus Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "1.5",
        "cost": "5300",
        "currency": "INR",
        "logoImage": "Venus.png",
        "status": "Unavailable",
        "flghtnumber": "VENU004"
    },
    {
        "name": "Earth Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "2",
        "cost": "5350",
        "currency": "INR",
        "logoImage": "Earth.png",
        "status": "Unavailable",
        "flghtnumber": "EART004"
    },
    {
        "name": "Mars Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "2.5",
        "cost": "5400",
        "currency": "INR",
        "logoImage": "Mars.png",
        "status": "Unavailable",
        "flghtnumber": "MARS004"
    },
    {
        "name": "Jupiter Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "3",
        "cost": "5450",
        "currency": "INR",
        "logoImage": "Jupiter.png",
        "status": "Unavailable",
        "flghtnumber": "JUPI004"
    },
    {
        "name": "Saturn Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "3.5",
        "cost": "5500",
        "currency": "INR",
        "logoImage": "Saturn.png",
        "status": "Unavailable",
        "flghtnumber": "SATU004"
    },
    {
        "name": "Uranus Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "4",
        "cost": "5550",
        "currency": "INR",
        "logoImage": "Uranus.png",
        "status": "Unavailable",
        "flghtnumber": "URAN004"
    },
    {
        "name": "Neptune Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "4.5",
        "cost": "5600",
        "currency": "INR",
        "logoImage": "Neptune.png",
        "status": "Unavailable",
        "flghtnumber": "NEPT004"
    },
    {
        "name": "Pluto Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "5",
        "cost": "5650",
        "currency": "INR",
        "logoImage": "Pluto.png",
        "status": "Unavailable",
        "flghtnumber": "PLUT004"
    },
    {
        "name": "Mercury Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "1",
        "cost": "5700",
        "currency": "INR",
        "logoImage": "Mercury.png",
        "status": "Check Status",
        "flghtnumber": "MERC004"
    },
    {
        "name": "Venus Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "1.5",
        "cost": "5750",
        "currency": "INR",
        "logoImage": "Venus.png",
        "status": "Check Status",
        "flghtnumber": "VENU004"
    },
    {
        "name": "Earth Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "2",
        "cost": "5800",
        "currency": "INR",
        "logoImage": "Earth.png",
        "status": "Check Status",
        "flghtnumber": "EART004"
    },
    {
        "name": "Mars Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "2.5",
        "cost": "5850",
        "currency": "INR",
        "logoImage": "Mars.png",
        "status": "Check Status",
        "flghtnumber": "MARS004"
    },
    {
        "name": "Jupiter Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "3",
        "cost": "5900",
        "currency": "INR",
        "logoImage": "Jupiter.png",
        "status": "Check Status",
        "flghtnumber": "JUPI004"
    },
    {
        "name": "Saturn Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "3.5",
        "cost": "5950",
        "currency": "INR",
        "logoImage": "Saturn.png",
        "status": "Check Status",
        "flghtnumber": "SATU004"
    },
    {
        "name": "Uranus Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "4",
        "cost": "6000",
        "currency": "INR",
        "logoImage": "Uranus.png",
        "status": "Check Status",
        "flghtnumber": "URAN004"
    },
    {
        "name": "Neptune Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "4.5",
        "cost": "6050",
        "currency": "INR",
        "logoImage": "Neptune.png",
        "status": "Check Status",
        "flghtnumber": "NEPT004"
    },
    {
        "name": "Pluto Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "5",
        "cost": "6100",
        "currency": "INR",
        "logoImage": "Pluto.png",
        "status": "Check Status",
        "flghtnumber": "PLUT004"
    },
    {
        "name": "Mercury Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "1",
        "cost": "6150",
        "currency": "INR",
        "logoImage": "Mercury.png",
        "status": "Checking Status",
        "flghtnumber": "MERC005"
    },
    {
        "name": "Venus Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "1.5",
        "cost": "6200",
        "currency": "INR",
        "logoImage": "Venus.png",
        "status": "Checking Status",
        "flghtnumber": "VENU005"
    },
    {
        "name": "Earth Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "2",
        "cost": "6250",
        "currency": "INR",
        "logoImage": "Earth.png",
        "status": "Checking Status",
        "flghtnumber": "EART005"
    },
    {
        "name": "Mars Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "2.5",
        "cost": "6300",
        "currency": "INR",
        "logoImage": "Mars.png",
        "status": "Checking Status",
        "flghtnumber": "MARS005"
    },
    {
        "name": "Jupiter Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "3",
        "cost": "6350",
        "currency": "INR",
        "logoImage": "Jupiter.png",
        "status": "Checking Status",
        "flghtnumber": "JUPI005"
    },
    {
        "name": "Saturn Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "3.5",
        "cost": "6400",
        "currency": "INR",
        "logoImage": "Saturn.png",
        "status": "Checking Status",
        "flghtnumber": "SATU005"
    },
    {
        "name": "Uranus Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "4",
        "cost": "6450",
        "currency": "INR",
        "logoImage": "Uranus.png",
        "status": "Checking Status",
        "flghtnumber": "URAN005"
    },
    {
        "name": "Neptune Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "4.5",
        "cost": "6500",
        "currency": "INR",
        "logoImage": "Neptune.png",
        "status": "Checking Status",
        "flghtnumber": "NEPT005"
    },
    {
        "name": "Pluto Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "5",
        "cost": "6550",
        "currency": "INR",
        "logoImage": "Pluto.png",
        "status": "Checking Status",
        "flghtnumber": "PLUT005"
    },
    {
        "name": "Mercury Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "1",
        "cost": "6600",
        "currency": "INR",
        "logoImage": "Mercury.png",
        "status": "Available Book Now",
        "flghtnumber": "MERC005"
    },
    {
        "name": "Venus Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "1.5",
        "cost": "6650",
        "currency": "INR",
        "logoImage": "Venus.png",
        "status": "Available Book Now",
        "flghtnumber": "VENU005"
    },
    {
        "name": "Earth Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "2",
        "cost": "6700",
        "currency": "INR",
        "logoImage": "Earth.png",
        "status": "Available Book Now",
        "flghtnumber": "EART005"
    },
    {
        "name": "Mars Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "2.5",
        "cost": "6750",
        "currency": "INR",
        "logoImage": "Mars.png",
        "status": "Available Book Now",
        "flghtnumber": "MARS005"
    },
    {
        "name": "Jupiter Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "3",
        "cost": "6800",
        "currency": "INR",
        "logoImage": "Jupiter.png",
        "status": "Available Book Now",
        "flghtnumber": "JUPI005"
    },
    {
        "name": "Saturn Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "3.5",
        "cost": "6850",
        "currency": "INR",
        "logoImage": "Saturn.png",
        "status": "Available Book Now",
        "flghtnumber": "SATU005"
    },
    {
        "name": "Uranus Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "4",
        "cost": "6900",
        "currency": "INR",
        "logoImage": "Uranus.png",
        "status": "Available Book Now",
        "flghtnumber": "URAN005"
    },
    {
        "name": "Neptune Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "4.5",
        "cost": "6950",
        "currency": "INR",
        "logoImage": "Neptune.png",
        "status": "Available Book Now",
        "flghtnumber": "NEPT005"
    },
    {
        "name": "Pluto Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "5",
        "cost": "7000",
        "currency": "INR",
        "logoImage": "Pluto.png",
        "status": "Available Book Now",
        "flghtnumber": "PLUT005"
    },
    {
        "name": "Mercury Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "1",
        "cost": "7050",
        "currency": "INR",
        "logoImage": "Mercury.png",
        "status": "Unavailable",
        "flghtnumber": "MERC006"
    },
    {
        "name": "Venus Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "1.5",
        "cost": "7100",
        "currency": "INR",
        "logoImage": "Venus.png",
        "status": "Unavailable",
        "flghtnumber": "VENU006"
    },
    {
        "name": "Earth Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "2",
        "cost": "7150",
        "currency": "INR",
        "logoImage": "Earth.png",
        "status": "Unavailable",
        "flghtnumber": "EART006"
    },
    {
        "name": "Mars Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "2.5",
        "cost": "7200",
        "currency": "INR",
        "logoImage": "Mars.png",
        "status": "Unavailable",
        "flghtnumber": "MARS006"
    },
    {
        "name": "Jupiter Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "3",
        "cost": "7250",
        "currency": "INR",
        "logoImage": "Jupiter.png",
        "status": "Unavailable",
        "flghtnumber": "JUPI006"
    },
    {
        "name": "Saturn Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "3.5",
        "cost": "7300",
        "currency": "INR",
        "logoImage": "Saturn.png",
        "status": "Unavailable",
        "flghtnumber": "SATU006"
    },
    {
        "name": "Uranus Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "4",
        "cost": "7350",
        "currency": "INR",
        "logoImage": "Uranus.png",
        "status": "Unavailable",
        "flghtnumber": "URAN006"
    },
    {
        "name": "Neptune Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "4.5",
        "cost": "7400",
        "currency": "INR",
        "logoImage": "Neptune.png",
        "status": "Unavailable",
        "flghtnumber": "NEPT006"
    },
    {
        "name": "Pluto Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "5",
        "cost": "7450",
        "currency": "INR",
        "logoImage": "Pluto.png",
        "status": "Unavailable",
        "flghtnumber": "PLUT006"
    },
    {
        "name": "Mercury Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "1",
        "cost": "7500",
        "currency": "INR",
        "logoImage": "Mercury.png",
        "status": "Check Status",
        "flghtnumber": "MERC006"
    },
    {
        "name": "Venus Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "1.5",
        "cost": "7550",
        "currency": "INR",
        "logoImage": "Venus.png",
        "status": "Check Status",
        "flghtnumber": "VENU006"
    },
    {
        "name": "Earth Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "2",
        "cost": "7600",
        "currency": "INR",
        "logoImage": "Earth.png",
        "status": "Check Status",
        "flghtnumber": "EART006"
    },
    {
        "name": "Mars Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "2.5",
        "cost": "7650",
        "currency": "INR",
        "logoImage": "Mars.png",
        "status": "Check Status",
        "flghtnumber": "MARS006"
    },
    {
        "name": "Jupiter Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "3",
        "cost": "7700",
        "currency": "INR",
        "logoImage": "Jupiter.png",
        "status": "Check Status",
        "flghtnumber": "JUPI006"
    },
    {
        "name": "Saturn Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "3.5",
        "cost": "7750",
        "currency": "INR",
        "logoImage": "Saturn.png",
        "status": "Check Status",
        "flghtnumber": "SATU006"
    },
    {
        "name": "Uranus Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "4",
        "cost": "7800",
        "currency": "INR",
        "logoImage": "Uranus.png",
        "status": "Check Status",
        "flghtnumber": "URAN006"
    },
    {
        "name": "Neptune Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "4.5",
        "cost": "7850",
        "currency": "INR",
        "logoImage": "Neptune.png",
        "status": "Check Status",
        "flghtnumber": "NEPT006"
    },
    {
        "name": "Pluto Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "5",
        "cost": "7900",
        "currency": "INR",
        "logoImage": "Pluto.png",
        "status": "Check Status",
        "flghtnumber": "PLUT006"
    },
    {
        "name": "Mercury Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "1",
        "cost": "7950",
        "currency": "INR",
        "logoImage": "Mercury.png",
        "status": "Checking Status",
        "flghtnumber": "MERC007"
    },
    {
        "name": "Venus Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "1.5",
        "cost": "8000",
        "currency": "INR",
        "logoImage": "Venus.png",
        "status": "Checking Status",
        "flghtnumber": "VENU007"
    },
    {
        "name": "Earth Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "2",
        "cost": "8050",
        "currency": "INR",
        "logoImage": "Earth.png",
        "status": "Checking Status",
        "flghtnumber": "EART007"
    },
    {
        "name": "Mars Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "2.5",
        "cost": "8100",
        "currency": "INR",
        "logoImage": "Mars.png",
        "status": "Checking Status",
        "flghtnumber": "MARS007"
    },
    {
        "name": "Jupiter Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "3",
        "cost": "8150",
        "currency": "INR",
        "logoImage": "Jupiter.png",
        "status": "Checking Status",
        "flghtnumber": "JUPI007"
    },
    {
        "name": "Saturn Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "3.5",
        "cost": "8200",
        "currency": "INR",
        "logoImage": "Saturn.png",
        "status": "Checking Status",
        "flghtnumber": "SATU007"
    },
    {
        "name": "Uranus Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "4",
        "cost": "8250",
        "currency": "INR",
        "logoImage": "Uranus.png",
        "status": "Checking Status",
        "flghtnumber": "URAN007"
    },
    {
        "name": "Neptune Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "4.5",
        "cost": "8300",
        "currency": "INR",
        "logoImage": "Neptune.png",
        "status": "Checking Status",
        "flghtnumber": "NEPT007"
    },
    {
        "name": "Pluto Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "5",
        "cost": "8350",
        "currency": "INR",
        "logoImage": "Pluto.png",
        "status": "Checking Status",
        "flghtnumber": "PLUT007"
    },
    {
        "name": "Mercury Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "1",
        "cost": "8400",
        "currency": "INR",
        "logoImage": "Mercury.png",
        "status": "Available Book Now",
        "flghtnumber": "MERC007"
    },
    {
        "name": "Venus Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "1.5",
        "cost": "8450",
        "currency": "INR",
        "logoImage": "Venus.png",
        "status": "Available Book Now",
        "flghtnumber": "VENU007"
    },
    {
        "name": "Earth Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "2",
        "cost": "8500",
        "currency": "INR",
        "logoImage": "Earth.png",
        "status": "Available Book Now",
        "flghtnumber": "EART007"
    },
    {
        "name": "Mars Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "2.5",
        "cost": "8550",
        "currency": "INR",
        "logoImage": "Mars.png",
        "status": "Available Book Now",
        "flghtnumber": "MARS007"
    },
    {
        "name": "Jupiter Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "3",
        "cost": "8600",
        "currency": "INR",
        "logoImage": "Jupiter.png",
        "status": "Available Book Now",
        "flghtnumber": "JUPI007"
    },
    {
        "name": "Saturn Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "3.5",
        "cost": "8650",
        "currency": "INR",
        "logoImage": "Saturn.png",
        "status": "Available Book Now",
        "flghtnumber": "SATU007"
    },
    {
        "name": "Uranus Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "4",
        "cost": "8700",
        "currency": "INR",
        "logoImage": "Uranus.png",
        "status": "Available Book Now",
        "flghtnumber": "URAN007"
    },
    {
        "name": "Neptune Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "4.5",
        "cost": "8750",
        "currency": "INR",
        "logoImage": "Neptune.png",
        "status": "Available Book Now",
        "flghtnumber": "NEPT007"
    },
    {
        "name": "Pluto Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "5",
        "cost": "8800",
        "currency": "INR",
        "logoImage": "Pluto.png",
        "status": "Available Book Now",
        "flghtnumber": "PLUT007"
    },
    {
        "name": "Mercury Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "1",
        "cost": "8850",
        "currency": "INR",
        "logoImage": "Mercury.png",
        "status": "Unavailable",
        "flghtnumber": "MERC008"
    },
    {
        "name": "Venus Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "1.5",
        "cost": "8900",
        "currency": "INR",
        "logoImage": "Venus.png",
        "status": "Unavailable",
        "flghtnumber": "VENU008"
    },
    {
        "name": "Earth Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "2",
        "cost": "8950",
        "currency": "INR",
        "logoImage": "Earth.png",
        "status": "Unavailable",
        "flghtnumber": "EART008"
    },
    {
        "name": "Mars Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "2.5",
        "cost": "9000",
        "currency": "INR",
        "logoImage": "Mars.png",
        "status": "Unavailable",
        "flghtnumber": "MARS008"
    },
    {
        "name": "Jupiter Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "3",
        "cost": "9050",
        "currency": "INR",
        "logoImage": "Jupiter.png",
        "status": "Unavailable",
        "flghtnumber": "JUPI008"
    },
    {
        "name": "Saturn Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "3.5",
        "cost": "9100",
        "currency": "INR",
        "logoImage": "Saturn.png",
        "status": "Unavailable",
        "flghtnumber": "SATU008"
    },
    {
        "name": "Uranus Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "4",
        "cost": "9150",
        "currency": "INR",
        "logoImage": "Uranus.png",
        "status": "Unavailable",
        "flghtnumber": "URAN008"
    },
    {
        "name": "Neptune Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "4.5",
        "cost": "9200",
        "currency": "INR",
        "logoImage": "Neptune.png",
        "status": "Unavailable",
        "flghtnumber": "NEPT008"
    },
    {
        "name": "Pluto Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "5",
        "cost": "9250",
        "currency": "INR",
        "logoImage": "Pluto.png",
        "status": "Unavailable",
        "flghtnumber": "PLUT008"
    },
    {
        "name": "Mercury Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "1",
        "cost": "9300",
        "currency": "INR",
        "logoImage": "Mercury.png",
        "status": "Check Status",
        "flghtnumber": "MERC008"
    },
    {
        "name": "Venus Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "1.5",
        "cost": "9350",
        "currency": "INR",
        "logoImage": "Venus.png",
        "status": "Check Status",
        "flghtnumber": "VENU008"
    },
    {
        "name": "Earth Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "2",
        "cost": "9400",
        "currency": "INR",
        "logoImage": "Earth.png",
        "status": "Check Status",
        "flghtnumber": "EART008"
    },
    {
        "name": "Mars Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "2.5",
        "cost": "9450",
        "currency": "INR",
        "logoImage": "Mars.png",
        "status": "Check Status",
        "flghtnumber": "MARS008"
    },
    {
        "name": "Jupiter Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "3",
        "cost": "9500",
        "currency": "INR",
        "logoImage": "Jupiter.png",
        "status": "Check Status",
        "flghtnumber": "JUPI008"
    },
    {
        "name": "Saturn Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "3.5",
        "cost": "9550",
        "currency": "INR",
        "logoImage": "Saturn.png",
        "status": "Check Status",
        "flghtnumber": "SATU008"
    },
    {
        "name": "Uranus Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "4",
        "cost": "9600",
        "currency": "INR",
        "logoImage": "Uranus.png",
        "status": "Check Status",
        "flghtnumber": "URAN008"
    },
    {
        "name": "Neptune Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "4.5",
        "cost": "9650",
        "currency": "INR",
        "logoImage": "Neptune.png",
        "status": "Check Status",
        "flghtnumber": "NEPT008"
    },
    {
        "name": "Pluto Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "5",
        "cost": "9700",
        "currency": "INR",
        "logoImage": "Pluto.png",
        "status": "Check Status",
        "flghtnumber": "PLUT008"
    },
    {
        "name": "Mercury Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "1",
        "cost": "9750",
        "currency": "INR",
        "logoImage": "Mercury.png",
        "status": "Checking Status",
        "flghtnumber": "MERC009"
    },
    {
        "name": "Venus Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "1.5",
        "cost": "9800",
        "currency": "INR",
        "logoImage": "Venus.png",
        "status": "Checking Status",
        "flghtnumber": "VENU009"
    },
    {
        "name": "Earth Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "2",
        "cost": "9850",
        "currency": "INR",
        "logoImage": "Earth.png",
        "status": "Checking Status",
        "flghtnumber": "EART009"
    },
    {
        "name": "Mars Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "2.5",
        "cost": "9900",
        "currency": "INR",
        "logoImage": "Mars.png",
        "status": "Checking Status",
        "flghtnumber": "MARS009"
    },
    {
        "name": "Jupiter Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "3",
        "cost": "9950",
        "currency": "INR",
        "logoImage": "Jupiter.png",
        "status": "Checking Status",
        "flghtnumber": "JUPI009"
    },
    {
        "name": "Saturn Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "3.5",
        "cost": "10000",
        "currency": "INR",
        "logoImage": "Saturn.png",
        "status": "Checking Status",
        "flghtnumber": "SATU009"
    },
    {
        "name": "Uranus Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "4",
        "cost": "10050",
        "currency": "INR",
        "logoImage": "Uranus.png",
        "status": "Checking Status",
        "flghtnumber": "URAN009"
    },
    {
        "name": "Neptune Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "4.5",
        "cost": "10100",
        "currency": "INR",
        "logoImage": "Neptune.png",
        "status": "Checking Status",
        "flghtnumber": "NEPT009"
    },
    {
        "name": "Pluto Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "5",
        "cost": "10150",
        "currency": "INR",
        "logoImage": "Pluto.png",
        "status": "Checking Status",
        "flghtnumber": "PLUT009"
    },
    {
        "name": "Mercury Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "1",
        "cost": "10200",
        "currency": "INR",
        "logoImage": "Mercury.png",
        "status": "Available Book Now",
        "flghtnumber": "MERC009"
    },
    {
        "name": "Venus Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "1.5",
        "cost": "10250",
        "currency": "INR",
        "logoImage": "Venus.png",
        "status": "Available Book Now",
        "flghtnumber": "VENU009"
    },
    {
        "name": "Earth Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "2",
        "cost": "10300",
        "currency": "INR",
        "logoImage": "Earth.png",
        "status": "Available Book Now",
        "flghtnumber": "EART009"
    },
    {
        "name": "Mars Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "2.5",
        "cost": "10350",
        "currency": "INR",
        "logoImage": "Mars.png",
        "status": "Available Book Now",
        "flghtnumber": "MARS009"
    },
    {
        "name": "Jupiter Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "3",
        "cost": "10400",
        "currency": "INR",
        "logoImage": "Jupiter.png",
        "status": "Available Book Now",
        "flghtnumber": "JUPI009"
    },
    {
        "name": "Saturn Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "3.5",
        "cost": "10450",
        "currency": "INR",
        "logoImage": "Saturn.png",
        "status": "Available Book Now",
        "flghtnumber": "SATU009"
    },
    {
        "name": "Uranus Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "4",
        "cost": "10500",
        "currency": "INR",
        "logoImage": "Uranus.png",
        "status": "Available Book Now",
        "flghtnumber": "URAN009"
    },
    {
        "name": "Neptune Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "4.5",
        "cost": "10550",
        "currency": "INR",
        "logoImage": "Neptune.png",
        "status": "Available Book Now",
        "flghtnumber": "NEPT009"
    },
    {
        "name": "Pluto Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "5",
        "cost": "10600",
        "currency": "INR",
        "logoImage": "Pluto.png",
        "status": "Available Book Now",
        "flghtnumber": "PLUT009"
    },
    {
        "name": "Mercury Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "1",
        "cost": "10650",
        "currency": "INR",
        "logoImage": "Mercury.png",
        "status": "Unavailable",
        "flghtnumber": "MERC010"
    },
    {
        "name": "Venus Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "1.5",
        "cost": "10700",
        "currency": "INR",
        "logoImage": "Venus.png",
        "status": "Unavailable",
        "flghtnumber": "VENU010"
    },
    {
        "name": "Earth Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "2",
        "cost": "10750",
        "currency": "INR",
        "logoImage": "Earth.png",
        "status": "Unavailable",
        "flghtnumber": "EART010"
    },
    {
        "name": "Mars Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "2.5",
        "cost": "10800",
        "currency": "INR",
        "logoImage": "Mars.png",
        "status": "Unavailable",
        "flghtnumber": "MARS010"
    },
    {
        "name": "Jupiter Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "3",
        "cost": "10850",
        "currency": "INR",
        "logoImage": "Jupiter.png",
        "status": "Unavailable",
        "flghtnumber": "JUPI010"
    },
    {
        "name": "Saturn Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "3.5",
        "cost": "10900",
        "currency": "INR",
        "logoImage": "Saturn.png",
        "status": "Unavailable",
        "flghtnumber": "SATU010"
    },
    {
        "name": "Uranus Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "4",
        "cost": "10950",
        "currency": "INR",
        "logoImage": "Uranus.png",
        "status": "Unavailable",
        "flghtnumber": "URAN010"
    },
    {
        "name": "Neptune Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "4.5",
        "cost": "11000",
        "currency": "INR",
        "logoImage": "Neptune.png",
        "status": "Unavailable",
        "flghtnumber": "NEPT010"
    },
    {
        "name": "Pluto Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "5",
        "cost": "11050",
        "currency": "INR",
        "logoImage": "Pluto.png",
        "status": "Unavailable",
        "flghtnumber": "PLUT010"
    },
    {
        "name": "Mercury Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "1",
        "cost": "11100",
        "currency": "INR",
        "logoImage": "Mercury.png",
        "status": "Check Status",
        "flghtnumber": "MERC010"
    },
    {
        "name": "Venus Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "1.5",
        "cost": "11150",
        "currency": "INR",
        "logoImage": "Venus.png",
        "status": "Check Status",
        "flghtnumber": "VENU010"
    },
    {
        "name": "Earth Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "2",
        "cost": "11200",
        "currency": "INR",
        "logoImage": "Earth.png",
        "status": "Check Status",
        "flghtnumber": "EART010"
    },
    {
        "name": "Mars Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "2.5",
        "cost": "11250",
        "currency": "INR",
        "logoImage": "Mars.png",
        "status": "Check Status",
        "flghtnumber": "MARS010"
    },
    {
        "name": "Jupiter Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "3",
        "cost": "11300",
        "currency": "INR",
        "logoImage": "Jupiter.png",
        "status": "Check Status",
        "flghtnumber": "JUPI010"
    },
    {
        "name": "Saturn Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "3.5",
        "cost": "11350",
        "currency": "INR",
        "logoImage": "Saturn.png",
        "status": "Check Status",
        "flghtnumber": "SATU010"
    },
    {
        "name": "Uranus Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "4",
        "cost": "11400",
        "currency": "INR",
        "logoImage": "Uranus.png",
        "status": "Check Status",
        "flghtnumber": "URAN010"
    },
    {
        "name": "Neptune Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "4.5",
        "cost": "11450",
        "currency": "INR",
        "logoImage": "Neptune.png",
        "status": "Check Status",
        "flghtnumber": "NEPT010"
    },
    {
        "name": "Pluto Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "5",
        "cost": "11500",
        "currency": "INR",
        "logoImage": "Pluto.png",
        "status": "Check Status",
        "flghtnumber": "PLUT010"
    },
    {
        "name": "Mercury Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "1",
        "cost": "11550",
        "currency": "INR",
        "logoImage": "Mercury.png",
        "status": "Checking Status",
        "flghtnumber": "MERC011"
    },
    {
        "name": "Venus Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "1.5",
        "cost": "11600",
        "currency": "INR",
        "logoImage": "Venus.png",
        "status": "Checking Status",
        "flghtnumber": "VENU011"
    },
    {
        "name": "Earth Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "2",
        "cost": "11650",
        "currency": "INR",
        "logoImage": "Earth.png",
        "status": "Checking Status",
        "flghtnumber": "EART011"
    },
    {
        "name": "Mars Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "2.5",
        "cost": "11700",
        "currency": "INR",
        "logoImage": "Mars.png",
        "status": "Checking Status",
        "flghtnumber": "MARS011"
    },
    {
        "name": "Jupiter Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "3",
        "cost": "11750",
        "currency": "INR",
        "logoImage": "Jupiter.png",
        "status": "Checking Status",
        "flghtnumber": "JUPI011"
    },
    {
        "name": "Saturn Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "3.5",
        "cost": "11800",
        "currency": "INR",
        "logoImage": "Saturn.png",
        "status": "Checking Status",
        "flghtnumber": "SATU011"
    },
    {
        "name": "Uranus Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "4",
        "cost": "11850",
        "currency": "INR",
        "logoImage": "Uranus.png",
        "status": "Checking Status",
        "flghtnumber": "URAN011"
    },
    {
        "name": "Neptune Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "4.5",
        "cost": "11900",
        "currency": "INR",
        "logoImage": "Neptune.png",
        "status": "Checking Status",
        "flghtnumber": "NEPT011"
    },
    {
        "name": "Pluto Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "5",
        "cost": "11950",
        "currency": "INR",
        "logoImage": "Pluto.png",
        "status": "Checking Status",
        "flghtnumber": "PLUT011"
    },
    {
        "name": "Mercury Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "1",
        "cost": "12000",
        "currency": "INR",
        "logoImage": "Mercury.png",
        "status": "Available Book Now",
        "flghtnumber": "MERC011"
    },
    {
        "name": "Venus Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "1.5",
        "cost": "12050",
        "currency": "INR",
        "logoImage": "Venus.png",
        "status": "Available Book Now",
        "flghtnumber": "VENU011"
    },
    {
        "name": "Earth Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "2",
        "cost": "12100",
        "currency": "INR",
        "logoImage": "Earth.png",
        "status": "Available Book Now",
        "flghtnumber": "EART011"
    },
    {
        "name": "Mars Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "2.5",
        "cost": "12150",
        "currency": "INR",
        "logoImage": "Mars.png",
        "status": "Available Book Now",
        "flghtnumber": "MARS011"
    },
    {
        "name": "Jupiter Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "3",
        "cost": "12200",
        "currency": "INR",
        "logoImage": "Jupiter.png",
        "status": "Available Book Now",
        "flghtnumber": "JUPI011"
    },
    {
        "name": "Saturn Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "3.5",
        "cost": "12250",
        "currency": "INR",
        "logoImage": "Saturn.png",
        "status": "Available Book Now",
        "flghtnumber": "SATU011"
    },
    {
        "name": "Uranus Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "4",
        "cost": "12300",
        "currency": "INR",
        "logoImage": "Uranus.png",
        "status": "Available Book Now",
        "flghtnumber": "URAN011"
    },
    {
        "name": "Neptune Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "4.5",
        "cost": "12350",
        "currency": "INR",
        "logoImage": "Neptune.png",
        "status": "Available Book Now",
        "flghtnumber": "NEPT011"
    },
    {
        "name": "Pluto Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "5",
        "cost": "12400",
        "currency": "INR",
        "logoImage": "Pluto.png",
        "status": "Available Book Now",
        "flghtnumber": "PLUT011"
    },
    {
        "name": "Mercury Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "1",
        "cost": "12450",
        "currency": "INR",
        "logoImage": "Mercury.png",
        "status": "Unavailable",
        "flghtnumber": "MERC012"
    },
    {
        "name": "Venus Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "1.5",
        "cost": "12500",
        "currency": "INR",
        "logoImage": "Venus.png",
        "status": "Unavailable",
        "flghtnumber": "VENU012"
    },
    {
        "name": "Earth Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "2",
        "cost": "12550",
        "currency": "INR",
        "logoImage": "Earth.png",
        "status": "Unavailable",
        "flghtnumber": "EART012"
    },
    {
        "name": "Mars Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "2.5",
        "cost": "12600",
        "currency": "INR",
        "logoImage": "Mars.png",
        "status": "Unavailable",
        "flghtnumber": "MARS012"
    },
    {
        "name": "Jupiter Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "3",
        "cost": "12650",
        "currency": "INR",
        "logoImage": "Jupiter.png",
        "status": "Unavailable",
        "flghtnumber": "JUPI012"
    },
    {
        "name": "Saturn Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "3.5",
        "cost": "12700",
        "currency": "INR",
        "logoImage": "Saturn.png",
        "status": "Unavailable",
        "flghtnumber": "SATU012"
    },
    {
        "name": "Uranus Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "4",
        "cost": "12750",
        "currency": "INR",
        "logoImage": "Uranus.png",
        "status": "Unavailable",
        "flghtnumber": "URAN012"
    },
    {
        "name": "Neptune Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "4.5",
        "cost": "12800",
        "currency": "INR",
        "logoImage": "Neptune.png",
        "status": "Unavailable",
        "flghtnumber": "NEPT012"
    },
    {
        "name": "Pluto Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "5",
        "cost": "12850",
        "currency": "INR",
        "logoImage": "Pluto.png",
        "status": "Unavailable",
        "flghtnumber": "PLUT012"
    },
    {
        "name": "Mercury Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "1",
        "cost": "12900",
        "currency": "INR",
        "logoImage": "Mercury.png",
        "status": "Check Status",
        "flghtnumber": "MERC012"
    },
    {
        "name": "Venus Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "1.5",
        "cost": "12950",
        "currency": "INR",
        "logoImage": "Venus.png",
        "status": "Check Status",
        "flghtnumber": "VENU012"
    },
    {
        "name": "Earth Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "2",
        "cost": "13000",
        "currency": "INR",
        "logoImage": "Earth.png",
        "status": "Check Status",
        "flghtnumber": "EART012"
    },
    {
        "name": "Mars Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "2.5",
        "cost": "13050",
        "currency": "INR",
        "logoImage": "Mars.png",
        "status": "Check Status",
        "flghtnumber": "MARS012"
    },
    {
        "name": "Jupiter Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "3",
        "cost": "13100",
        "currency": "INR",
        "logoImage": "Jupiter.png",
        "status": "Check Status",
        "flghtnumber": "JUPI012"
    },
    {
        "name": "Saturn Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "3.5",
        "cost": "13150",
        "currency": "INR",
        "logoImage": "Saturn.png",
        "status": "Check Status",
        "flghtnumber": "SATU012"
    },
    {
        "name": "Uranus Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "4",
        "cost": "13200",
        "currency": "INR",
        "logoImage": "Uranus.png",
        "status": "Check Status",
        "flghtnumber": "URAN012"
    },
    {
        "name": "Neptune Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "4.5",
        "cost": "13250",
        "currency": "INR",
        "logoImage": "Neptune.png",
        "status": "Check Status",
        "flghtnumber": "NEPT012"
    },
    {
        "name": "Pluto Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "5",
        "cost": "13300",
        "currency": "INR",
        "logoImage": "Pluto.png",
        "status": "Check Status",
        "flghtnumber": "PLUT012"
    },
    {
        "name": "Mercury Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "1",
        "cost": "13350",
        "currency": "INR",
        "logoImage": "Mercury.png",
        "status": "Checking Status",
        "flghtnumber": "MERC013"
    },
    {
        "name": "Venus Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "1.5",
        "cost": "13400",
        "currency": "INR",
        "logoImage": "Venus.png",
        "status": "Checking Status",
        "flghtnumber": "VENU013"
    },
    {
        "name": "Earth Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "2",
        "cost": "13450",
        "currency": "INR",
        "logoImage": "Earth.png",
        "status": "Checking Status",
        "flghtnumber": "EART013"
    },
    {
        "name": "Mars Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "2.5",
        "cost": "13500",
        "currency": "INR",
        "logoImage": "Mars.png",
        "status": "Checking Status",
        "flghtnumber": "MARS013"
    },
    {
        "name": "Jupiter Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "3",
        "cost": "13550",
        "currency": "INR",
        "logoImage": "Jupiter.png",
        "status": "Checking Status",
        "flghtnumber": "JUPI013"
    },
    {
        "name": "Saturn Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "3.5",
        "cost": "13600",
        "currency": "INR",
        "logoImage": "Saturn.png",
        "status": "Checking Status",
        "flghtnumber": "SATU013"
    },
    {
        "name": "Uranus Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "4",
        "cost": "13650",
        "currency": "INR",
        "logoImage": "Uranus.png",
        "status": "Checking Status",
        "flghtnumber": "URAN013"
    },
    {
        "name": "Neptune Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "4.5",
        "cost": "13700",
        "currency": "INR",
        "logoImage": "Neptune.png",
        "status": "Checking Status",
        "flghtnumber": "NEPT013"
    },
    {
        "name": "Pluto Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "5",
        "cost": "13750",
        "currency": "INR",
        "logoImage": "Pluto.png",
        "status": "Checking Status",
        "flghtnumber": "PLUT013"
    },
    {
        "name": "Mercury Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "1",
        "cost": "13800",
        "currency": "INR",
        "logoImage": "Mercury.png",
        "status": "Available Book Now",
        "flghtnumber": "MERC013"
    },
    {
        "name": "Venus Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "1.5",
        "cost": "13850",
        "currency": "INR",
        "logoImage": "Venus.png",
        "status": "Available Book Now",
        "flghtnumber": "VENU013"
    },
    {
        "name": "Earth Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "2",
        "cost": "13900",
        "currency": "INR",
        "logoImage": "Earth.png",
        "status": "Available Book Now",
        "flghtnumber": "EART013"
    },
    {
        "name": "Mars Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "2.5",
        "cost": "13950",
        "currency": "INR",
        "logoImage": "Mars.png",
        "status": "Available Book Now",
        "flghtnumber": "MARS013"
    },
    {
        "name": "Jupiter Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "3",
        "cost": "14000",
        "currency": "INR",
        "logoImage": "Jupiter.png",
        "status": "Available Book Now",
        "flghtnumber": "JUPI013"
    },
    {
        "name": "Saturn Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "3.5",
        "cost": "14050",
        "currency": "INR",
        "logoImage": "Saturn.png",
        "status": "Available Book Now",
        "flghtnumber": "SATU013"
    },
    {
        "name": "Uranus Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "4",
        "cost": "14100",
        "currency": "INR",
        "logoImage": "Uranus.png",
        "status": "Available Book Now",
        "flghtnumber": "URAN013"
    },
    {
        "name": "Neptune Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "4.5",
        "cost": "14150",
        "currency": "INR",
        "logoImage": "Neptune.png",
        "status": "Available Book Now",
        "flghtnumber": "NEPT013"
    },
    {
        "name": "Pluto Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "5",
        "cost": "14200",
        "currency": "INR",
        "logoImage": "Pluto.png",
        "status": "Available Book Now",
        "flghtnumber": "PLUT013"
    },
    {
        "name": "Mercury Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "1",
        "cost": "14250",
        "currency": "INR",
        "logoImage": "Mercury.png",
        "status": "Unavailable",
        "flghtnumber": "MERC014"
    },
    {
        "name": "Venus Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "1.5",
        "cost": "14300",
        "currency": "INR",
        "logoImage": "Venus.png",
        "status": "Unavailable",
        "flghtnumber": "VENU014"
    },
    {
        "name": "Earth Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "2",
        "cost": "14350",
        "currency": "INR",
        "logoImage": "Earth.png",
        "status": "Unavailable",
        "flghtnumber": "EART014"
    },
    {
        "name": "Mars Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "2.5",
        "cost": "14400",
        "currency": "INR",
        "logoImage": "Mars.png",
        "status": "Unavailable",
        "flghtnumber": "MARS014"
    },
    {
        "name": "Jupiter Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "3",
        "cost": "14450",
        "currency": "INR",
        "logoImage": "Jupiter.png",
        "status": "Unavailable",
        "flghtnumber": "JUPI014"
    },
    {
        "name": "Saturn Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "3.5",
        "cost": "14500",
        "currency": "INR",
        "logoImage": "Saturn.png",
        "status": "Unavailable",
        "flghtnumber": "SATU014"
    },
    {
        "name": "Uranus Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "4",
        "cost": "14550",
        "currency": "INR",
        "logoImage": "Uranus.png",
        "status": "Unavailable",
        "flghtnumber": "URAN014"
    },
    {
        "name": "Neptune Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "4.5",
        "cost": "14600",
        "currency": "INR",
        "logoImage": "Neptune.png",
        "status": "Unavailable",
        "flghtnumber": "NEPT014"
    },
    {
        "name": "Pluto Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "5",
        "cost": "14650",
        "currency": "INR",
        "logoImage": "Pluto.png",
        "status": "Unavailable",
        "flghtnumber": "PLUT014"
    },
    {
        "name": "Mercury Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "1",
        "cost": "14700",
        "currency": "INR",
        "logoImage": "Mercury.png",
        "status": "Check Status",
        "flghtnumber": "MERC014"
    },
    {
        "name": "Venus Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "1.5",
        "cost": "14750",
        "currency": "INR",
        "logoImage": "Venus.png",
        "status": "Check Status",
        "flghtnumber": "VENU014"
    },
    {
        "name": "Earth Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "2",
        "cost": "14800",
        "currency": "INR",
        "logoImage": "Earth.png",
        "status": "Check Status",
        "flghtnumber": "EART014"
    },
    {
        "name": "Mars Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "2.5",
        "cost": "14850",
        "currency": "INR",
        "logoImage": "Mars.png",
        "status": "Check Status",
        "flghtnumber": "MARS014"
    },
    {
        "name": "Jupiter Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "3",
        "cost": "14900",
        "currency": "INR",
        "logoImage": "Jupiter.png",
        "status": "Check Status",
        "flghtnumber": "JUPI014"
    },
    {
        "name": "Saturn Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "3.5",
        "cost": "14950",
        "currency": "INR",
        "logoImage": "Saturn.png",
        "status": "Check Status",
        "flghtnumber": "SATU014"
    },
    {
        "name": "Uranus Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "4",
        "cost": "15000",
        "currency": "INR",
        "logoImage": "Uranus.png",
        "status": "Check Status",
        "flghtnumber": "URAN014"
    },
    {
        "name": "Neptune Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "4.5",
        "cost": "15050",
        "currency": "INR",
        "logoImage": "Neptune.png",
        "status": "Check Status",
        "flghtnumber": "NEPT014"
    },
    {
        "name": "Pluto Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "5",
        "cost": "15100",
        "currency": "INR",
        "logoImage": "Pluto.png",
        "status": "Check Status",
        "flghtnumber": "PLUT014"
    },
    {
        "name": "Mercury Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "1",
        "cost": "15150",
        "currency": "INR",
        "logoImage": "Mercury.png",
        "status": "Checking Status",
        "flghtnumber": "MERC015"
    },
    {
        "name": "Venus Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "1.5",
        "cost": "15200",
        "currency": "INR",
        "logoImage": "Venus.png",
        "status": "Checking Status",
        "flghtnumber": "VENU015"
    },
    {
        "name": "Earth Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "2",
        "cost": "15250",
        "currency": "INR",
        "logoImage": "Earth.png",
        "status": "Checking Status",
        "flghtnumber": "EART015"
    },
    {
        "name": "Mars Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "2.5",
        "cost": "15300",
        "currency": "INR",
        "logoImage": "Mars.png",
        "status": "Checking Status",
        "flghtnumber": "MARS015"
    },
    {
        "name": "Jupiter Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "3",
        "cost": "15350",
        "currency": "INR",
        "logoImage": "Jupiter.png",
        "status": "Checking Status",
        "flghtnumber": "JUPI015"
    },
    {
        "name": "Saturn Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "3.5",
        "cost": "15400",
        "currency": "INR",
        "logoImage": "Saturn.png",
        "status": "Checking Status",
        "flghtnumber": "SATU015"
    },
    {
        "name": "Uranus Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "4",
        "cost": "15450",
        "currency": "INR",
        "logoImage": "Uranus.png",
        "status": "Checking Status",
        "flghtnumber": "URAN015"
    },
    {
        "name": "Neptune Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "4.5",
        "cost": "15500",
        "currency": "INR",
        "logoImage": "Neptune.png",
        "status": "Checking Status",
        "flghtnumber": "NEPT015"
    },
    {
        "name": "Pluto Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "5",
        "cost": "15550",
        "currency": "INR",
        "logoImage": "Pluto.png",
        "status": "Checking Status",
        "flghtnumber": "PLUT015"
    },
    {
        "name": "Mercury Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "1",
        "cost": "15600",
        "currency": "INR",
        "logoImage": "Mercury.png",
        "status": "Available Book Now",
        "flghtnumber": "MERC015"
    },
    {
        "name": "Venus Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "1.5",
        "cost": "15650",
        "currency": "INR",
        "logoImage": "Venus.png",
        "status": "Available Book Now",
        "flghtnumber": "VENU015"
    },
    {
        "name": "Earth Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "2",
        "cost": "15700",
        "currency": "INR",
        "logoImage": "Earth.png",
        "status": "Available Book Now",
        "flghtnumber": "EART015"
    },
    {
        "name": "Mars Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "2.5",
        "cost": "15750",
        "currency": "INR",
        "logoImage": "Mars.png",
        "status": "Available Book Now",
        "flghtnumber": "MARS015"
    },
    {
        "name": "Jupiter Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "3",
        "cost": "15800",
        "currency": "INR",
        "logoImage": "Jupiter.png",
        "status": "Available Book Now",
        "flghtnumber": "JUPI015"
    },
    {
        "name": "Saturn Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "3.5",
        "cost": "15850",
        "currency": "INR",
        "logoImage": "Saturn.png",
        "status": "Available Book Now",
        "flghtnumber": "SATU015"
    },
    {
        "name": "Uranus Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "4",
        "cost": "15900",
        "currency": "INR",
        "logoImage": "Uranus.png",
        "status": "Available Book Now",
        "flghtnumber": "URAN015"
    },
    {
        "name": "Neptune Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "4.5",
        "cost": "15950",
        "currency": "INR",
        "logoImage": "Neptune.png",
        "status": "Available Book Now",
        "flghtnumber": "NEPT015"
    },
    {
        "name": "Pluto Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "5",
        "cost": "16000",
        "currency": "INR",
        "logoImage": "Pluto.png",
        "status": "Available Book Now",
        "flghtnumber": "PLUT015"
    },
    {
        "name": "Mercury Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "1",
        "cost": "16050",
        "currency": "INR",
        "logoImage": "Mercury.png",
        "status": "Unavailable",
        "flghtnumber": "MERC016"
    },
    {
        "name": "Venus Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "1.5",
        "cost": "16100",
        "currency": "INR",
        "logoImage": "Venus.png",
        "status": "Unavailable",
        "flghtnumber": "VENU016"
    },
    {
        "name": "Earth Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "2",
        "cost": "16150",
        "currency": "INR",
        "logoImage": "Earth.png",
        "status": "Unavailable",
        "flghtnumber": "EART016"
    },
    {
        "name": "Mars Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "2.5",
        "cost": "16200",
        "currency": "INR",
        "logoImage": "Mars.png",
        "status": "Unavailable",
        "flghtnumber": "MARS016"
    },
    {
        "name": "Jupiter Airlines",
        "departure": "SIN",
        "arrival": "DXB",
        "duration": "6.5",
        "rating": "3",
        "cost": "16250",
        "currency": "INR",
        "logoImage": "Jupiter.png",
        "status": "Unavailable",
        "flghtnumber": "JUPI016"
    },
    {
        "name": "Saturn Airlines",
        "departure": "DEL",
        "arrival": "BOM",
        "duration": "2.5",
        "rating": "3.5",
        "cost": "16300",
        "currency": "INR",
        "logoImage": "Saturn.png",
        "status": "Unavailable",
        "flghtnumber": "SATU016"
    },
    {
        "name": "Uranus Airlines",
        "departure": "MAA",
        "arrival": "BOM",
        "duration": "1.5",
        "rating": "4",
        "cost": "16350",
        "currency": "INR",
        "logoImage": "Uranus.png",
        "status": "Unavailable",
        "flghtnumber": "URAN016"
    },
    {
        "name": "Neptune Airlines",
        "departure": "BOM",
        "arrival": "DXB",
        "duration": "3",
        "rating": "4.5",
        "cost": "16400",
        "currency": "INR",
        "logoImage": "Neptune.png",
        "status": "Unavailable",
        "flghtnumber": "NEPT016"
    }
]